'use strict';

module.exports = {
    BUTTON_VOLUME_PLUS_KEY_CODE: 447,
    BUTTON_VOLUME_MINUS_KEY_CODE: 448,
    BUTTON_PROGRAM_PLUS_KEY_CODE: 427,
    BUTTON_PROGRAM_MINUS_KEY_CODE: 428,
    BUTTON_HOME_KEY_CODE: 462,
    BUTTON_BACK_KEY_CODE: 461,
    BUTTON_POWER_KEY_CODE: 409,
    BUTTON_FFW_KEY_CODE: 417,
    BUTTON_FRW_KEY_CODE: 412,
    BUTTON_PLAY_PAUSE_KEY_CODE: 415,
    BUTTON_STOP_KEY_CODE: 413,
    BUTTON_OPTIONS_KEY_CODE: 457,
    BUTTON_REC_KEY_CODE: 416,
    BUTTON_MUTE_KEY_CODE: 44,
    BUTTON_0_KEY_CODE: 48,
    BUTTON_1_KEY_CODE: 49,
    BUTTON_2_KEY_CODE: 50,
    BUTTON_3_KEY_CODE: 51,
    BUTTON_4_KEY_CODE: 52,
    BUTTON_5_KEY_CODE: 53,
    BUTTON_6_KEY_CODE: 54,
    BUTTON_7_KEY_CODE: 55,
    BUTTON_8_KEY_CODE: 56,
    BUTTON_9_KEY_CODE: 57
};